# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'SeminarViro' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for SeminarViro

  target 'SeminarViroTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'ViroKit_static_lib', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/static_lib'

end

target 'SeminarViro-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for SeminarViro-tvOS

  target 'SeminarViro-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
